### ISSUE TITLE
Load Error when jekyll tries to install generate-projects.rb

### ISSUE THREAD

**Issue by jputrino** [recurser/jekyll-plugins#34]
I got the following message when jekyll tried to install the generate-projects.rb (I'm running the build in Travis CI):

```
home/travis/build/jputrino/f5-openstack-docs/_plugins/generate_projects.rb:64:in `require': cannot load such file -- zip/zip (LoadError)
    from /home/travis/build/jputrino/f5-openstack-docs/_plugins/generate_projects.rb:64:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `require'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `block (2 levels) in require_plugin_files'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `each'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `each'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `require_plugin_files'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /home/travis/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

The command "./script/cibuild.sh" exited with 1.
```

**Comment by xylo** [comment]
You need to install the ruby zip library:

```
gem install zip
```

**Comment by lizrush** [comment]
I also ran into this problem and `gem install zip` didn't really cut it for me. Because Rubyzip was updated with a major release, there is no backwards compatibility (they removed the Zip prefix in class names, which you can see in this plugin). See this note at the [rubyzip repo](https://github.com/rubyzip/rubyzip#important-note).

**Comment by recurser** [comment]
Apologies for the (huge) delay here. This project is no longer maintained, and I'm archiving it.
